# **Data**

| العمود              | المعنى                                                       | النوع                      |
| ------------------- | ------------------------------------------------------------ | -------------------------- |
| `dur`               | مدة الاتصال/التدفق بالثواني                                  | Numerical                  |
| `proto`             | بروتوكول الاتصال مثل TCP, UDP, ICMP                          | Categorical                |
| `service`           | الخدمة المستخدمة مثل HTTP, FTP, DNS                          | Categorical                |
| `state`             | حالة الاتصال مثل FIN, CON, INT                               | Categorical                |
| `spkts`             | عدد الـ Packets المرسلة من المصدر                            | Numerical                  |
| `dpkts`             | عدد الـ Packets المرسلة من الوجهة                            | Numerical                  |
| `sbytes`            | عدد الـ Bytes المرسلة من المصدر                              | Numerical                  |
| `dbytes`            | عدد الـ Bytes المرسلة من الوجهة                              | Numerical                  |
| `rate`              | معدل نقل البيانات/الحزم في الاتصال                           | Numerical                  |
| `sload`             | معدل تحميل البيانات من المصدر                                | Numerical                  |
| `dload`             | معدل تحميل البيانات من الوجهة                                | Numerical                  |
| `sloss`             | عدد الـ Packets المفقودة من المصدر                           | Numerical                  |
| `dloss`             | عدد الـ Packets المفقودة من الوجهة                           | Numerical                  |
| `sinpkt`            | متوسط الزمن بين Packets المصدر                               | Numerical                  |
| `dinpkt`            | متوسط الزمن بين Packets الوجهة                               | Numerical                  |
| `sjit`              | مقدار التذبذب (Jitter) في Packets المصدر                     | Numerical                  |
| `djit`              | مقدار التذبذب (Jitter) في Packets الوجهة                     | Numerical                  |
| `swin`              | حجم نافذة TCP للمصدر                                         | Numerical                  |
| `stcpb`             | رقم TCP sequence الأولي للمصدر                               | Numerical                  |
| `dtcpb`             | رقم TCP sequence الأولي للوجهة                               | Numerical                  |
| `dwin`              | حجم نافذة TCP للوجهة                                         | Numerical                  |
| `tcprtt`            | وقت Round Trip في اتصال TCP                                  | Numerical                  |
| `synack`            | الزمن بين SYN و SYN/ACK                                      | Numerical                  |
| `ackdat`            | الزمن بين SYN/ACK و ACK                                      | Numerical                  |
| `smean`             | متوسط حجم الحزم المرسلة من المصدر                            | Numerical                  |
| `dmean`             | متوسط حجم الحزم المرسلة من الوجهة                            | Numerical                  |
| `trans_depth`       | عمق المعاملة داخل بروتوكول HTTP                              | Numerical                  |
| `response_body_len` | حجم محتوى الـ Response                                       | Numerical                  |
| `ct_src_dport_ltm`  | عدد الاتصالات الحديثة من نفس المصدر إلى نفس Destination Port | Numerical                  |
| `ct_dst_sport_ltm`  | عدد الاتصالات الحديثة إلى نفس Source Port                    | Numerical                  |
| `is_ftp_login`      | هل حدث تسجيل دخول FTP أم لا                                  | Binary                     |
| `ct_ftp_cmd`        | عدد أوامر FTP في الاتصال                                     | Numerical                  |
| `ct_flw_http_mthd`  | عدد طرق HTTP المستخدمة مثل GET/POST                          | Numerical                  |
| `is_sm_ips_ports`   | هل المصدر والوجهة يستخدمان نفس IP/Port                       | Binary                     |
| `attack_cat`        | نوع الهجوم مثل DoS, Exploits, Fuzzers                        | Categorical / Target محتمل |
| `label`             | هل الاتصال طبيعي أم هجوم                                     | Binary / Target            |

# **Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data = pd.read_parquet("UNSW_NB15_training-set.parquet")

# **EDA**

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                175341 non-null  float32
 1   proto              175341 non-null  category
 2   service            175341 non-null  category
 3   state              175341 non-null  category
 4   spkts              175341 non-null  int16
 5   dpkts              175341 non-null  int16
 6   sbytes             175341 non-null  int32
 7   dbytes             175341 non-null  int32
 8   rate               175341 non-null  float32
 9   sload              175341 non-null  float32
 10  dload              175341 non-null  float32
 11  sloss              175341 non-null  int16
 12  dloss              175341 non-null  int16
 13  sinpkt             175341 non-null  float32
 14  dinpkt             175341 non-null  float32
 15  sjit               175341 non-null  float32
 16  djit               175341 non-null  float32
 17  swin               175341 non-null  int16
 18  stcpb              175341 non-null  int64
 19  dtcpb              175341 non-null  int64
 20  dwin               175341 non-null  int16
 21  tcprtt             175341 non-null  float32
 22  synack             175341 non-null  float32
 23  ackdat             175341 non-null  float32
 24  smean              175341 non-null  int16
 25  dmean              175341 non-null  int16
 26  trans_depth        175341 non-null  int16
 27  response_body_len  175341 non-null  int32
 28  ct_src_dport_ltm   175341 non-null  int8
 29  ct_dst_sport_ltm   175341 non-null  int8
 30  is_ftp_login       175341 non-null  int8
 31  ct_ftp_cmd         175341 non-null  int8
 32  ct_flw_http_mthd   175341 non-null  int8
 33  is_sm_ips_ports    175341 non-null  int8
 34  attack_cat         175341 non-null  category
 35  label              175341 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 17.1 MB

In [4]:
train_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087486,14158.942383,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473373,8395.112305,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.271851,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.178955,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.499023,...,0,0,2,1,0,0,0,0,Normal,0

In [5]:
train_data.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt',
       'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt',
       'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_src_dport_ltm', 'ct_dst_sport_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'is_sm_ips_ports',
       'attack_cat', 'label'],
      dtype='object')

# **Visualization**

In [6]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="dur" , y="sbytes",hue="label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="dur" , y="sbytes",hue="label")'

In [7]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="dur" , y="dbytes",hue="label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="dur" , y="dbytes",hue="label")'

In [8]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="dur" , y="dbytes",hue="label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="dur" , y="dbytes",hue="label")'

In [9]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="rate" , y="sbytes" , hue="label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="rate" , y="sbytes" , hue="label")'

In [10]:
"""plt.figure(figsize=(20,8))
sns.histplot(train_data , x = "attack_cat")"""

'plt.figure(figsize=(20,8))\nsns.histplot(train_data , x = "attack_cat")'

In [11]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x = "dur" , y = "ct_src_dport_ltm" ,hue="label" )"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x = "dur" , y = "ct_src_dport_ltm" ,hue="label" )'

In [12]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x = "dur" , y = "ct_dst_sport_ltm" ,hue="label" )"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x = "dur" , y = "ct_dst_sport_ltm" ,hue="label" )'

In [13]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="sload" , y="sloss" , hue = "label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="sload" , y="sloss" , hue = "label")'

In [14]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="dload" , y="dloss" , hue = "label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="dload" , y="dloss" , hue = "label")'

In [15]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="tcprtt" , y="label",hue = "attack_cat")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="tcprtt" , y="label",hue = "attack_cat")'

In [16]:
"""train_data["attack_cat"].value_counts()"""

'train_data["attack_cat"].value_counts()'

In [17]:
"""train_data["attack_cat"].value_counts().plot(kind="pie")"""

'train_data["attack_cat"].value_counts().plot(kind="pie")'

In [18]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="djit" , y="dwin",hue = "label")"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="djit" , y="dwin",hue = "label")'

In [19]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="synack" , y="rate" ,hue="label" )"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="synack" , y="rate" ,hue="label" )'

In [20]:
"""train_data.columns"""

'train_data.columns'

In [21]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="ackdat" , y="dpkts" ,hue="label" )"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="ackdat" , y="dpkts" ,hue="label" )'

In [22]:
"""plt.figure(figsize=(20,8))
sns.scatterplot(train_data , x="ackdat" , y="spkts" ,hue="label" )"""

'plt.figure(figsize=(20,8))\nsns.scatterplot(train_data , x="ackdat" , y="spkts" ,hue="label" )'

# **Cleaning Data**

In [23]:
train_data.duplicated().sum()

np.int64(78519)

In [24]:
train_data.drop_duplicates(inplace=True)

In [25]:
train_data.reset_index(inplace=True , drop=True)

In [26]:
train_data.isna().sum().sort_values(ascending=False).head()

dur        0
proto      0
service    0
state      0
spkts      0
dtype: int64

In [27]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96822 entries, 0 to 96821
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   dur                96822 non-null  float32
 1   proto              96822 non-null  category
 2   service            96822 non-null  category
 3   state              96822 non-null  category
 4   spkts              96822 non-null  int16
 5   dpkts              96822 non-null  int16
 6   sbytes             96822 non-null  int32
 7   dbytes             96822 non-null  int32
 8   rate               96822 non-null  float32
 9   sload              96822 non-null  float32
 10  dload              96822 non-null  float32
 11  sloss              96822 non-null  int16
 12  dloss              96822 non-null  int16
 13  sinpkt             96822 non-null  float32
 14  dinpkt             96822 non-null  float32
 15  sjit               96822 non-null  float32
 16  djit               96822 non-null  float32
 17  swin               96822 non-null  int16
 18  stcpb              96822 non-null  int64
 19  dtcpb              96822 non-null  int64
 20  dwin               96822 non-null  int16
 21  tcprtt             96822 non-null  float32
 22  synack             96822 non-null  float32
 23  ackdat             96822 non-null  float32
 24  smean              96822 non-null  int16
 25  dmean              96822 non-null  int16
 26  trans_depth        96822 non-null  int16
 27  response_body_len  96822 non-null  int32
 28  ct_src_dport_ltm   96822 non-null  int8
 29  ct_dst_sport_ltm   96822 non-null  int8
 30  is_ftp_login       96822 non-null  int8
 31  ct_ftp_cmd         96822 non-null  int8
 32  ct_flw_http_mthd   96822 non-null  int8
 33  is_sm_ips_ports    96822 non-null  int8
 34  attack_cat         96822 non-null  category
 35  label              96822 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 9.4 MB

# **Balancing Data**

In [28]:
normal_train = train_data[train_data["label"]==0]
normal_train.reset_index(drop=True , inplace= True)
attacked_train = train_data[train_data["label"]==1]
attacked_train.reset_index(drop=True , inplace= True)
print(normal_train.shape)
print(attacked_train.shape)

(48894, 36)
(47928, 36)

In [29]:
balanced_data =pd.concat([normal_train,attacked_train],axis=0)
balanced_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087486,14158.942383,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473373,8395.112305,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.271851,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.178955,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.499023,...,0,0,2,1,0,0,0,0,Normal,0

In [30]:
shuffled_balanced_data = balanced_data.sample(frac=1.0, random_state=42).reset_index(drop=True)
shuffled_balanced_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.039908,tcp,-,FIN,90,92,5174,83812,4535.431641,1.025759e+06,...,0,0,1,1,0,0,0,0,Normal,0
1,0.741610,tcp,-,FIN,10,8,564,354,22.923100,5.479969e+03,...,0,0,1,1,0,0,0,0,Reconnaissance,1
2,1.392597,tcp,http,FIN,26,114,1492,143455,99.813515,8.243591e+03,...,1,69194,1,1,0,0,1,0,Exploits,1
3,0.013721,tcp,-,FIN,16,18,1540,1644,2405.072510,8.419211e+05,...,0,0,4,1,0,0,0,0,Normal,0
4,4.681455,tcp,ftp,FIN,24,22,1240,1630,9.612396,2.031847e+03,...,0,0,1,1,1,1,0,0,Exploits,1

In [31]:
shuffled_balanced_data.to_csv("balnced_data.csv",index=False)

In [32]:
shuffled_balanced_data.drop("attack_cat" , axis=1 , inplace=True)
shuffled_balanced_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,dmean,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,label
0,0.039908,tcp,-,FIN,90,92,5174,83812,4535.431641,1.025759e+06,...,911,0,0,1,1,0,0,0,0,0
1,0.741610,tcp,-,FIN,10,8,564,354,22.923100,5.479969e+03,...,44,0,0,1,1,0,0,0,0,1
2,1.392597,tcp,http,FIN,26,114,1492,143455,99.813515,8.243591e+03,...,1258,1,69194,1,1,0,0,1,0,1
3,0.013721,tcp,-,FIN,16,18,1540,1644,2405.072510,8.419211e+05,...,91,0,0,4,1,0,0,0,0,0
4,4.681455,tcp,ftp,FIN,24,22,1240,1630,9.612396,2.031847e+03,...,74,0,0,1,1,1,1,0,0,1

In [33]:
shuffled_balanced_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96822 entries, 0 to 96821
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   dur                96822 non-null  float32
 1   proto              96822 non-null  category
 2   service            96822 non-null  category
 3   state              96822 non-null  category
 4   spkts              96822 non-null  int16
 5   dpkts              96822 non-null  int16
 6   sbytes             96822 non-null  int32
 7   dbytes             96822 non-null  int32
 8   rate               96822 non-null  float32
 9   sload              96822 non-null  float32
 10  dload              96822 non-null  float32
 11  sloss              96822 non-null  int16
 12  dloss              96822 non-null  int16
 13  sinpkt             96822 non-null  float32
 14  dinpkt             96822 non-null  float32
 15  sjit               96822 non-null  float32
 16  djit               96822 non-null  float32
 17  swin               96822 non-null  int16
 18  stcpb              96822 non-null  int64
 19  dtcpb              96822 non-null  int64
 20  dwin               96822 non-null  int16
 21  tcprtt             96822 non-null  float32
 22  synack             96822 non-null  float32
 23  ackdat             96822 non-null  float32
 24  smean              96822 non-null  int16
 25  dmean              96822 non-null  int16
 26  trans_depth        96822 non-null  int16
 27  response_body_len  96822 non-null  int32
 28  ct_src_dport_ltm   96822 non-null  int8
 29  ct_dst_sport_ltm   96822 non-null  int8
 30  is_ftp_login       96822 non-null  int8
 31  ct_ftp_cmd         96822 non-null  int8
 32  ct_flw_http_mthd   96822 non-null  int8
 33  is_sm_ips_ports    96822 non-null  int8
 34  label              96822 non-null  int8
dtypes: category(3), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 9.3 MB

In [34]:
shuffled_balanced_data["proto"].unique()

['tcp', 'udp', 'ospf', '3pc', 'vrrp', ..., 'ddp', 'dcn', 'ipv6-no', 'qnx', 'rtp']
Length: 133
Categories (133, object): ['3pc', 'a/n', 'aes-sp3-d', 'any', ..., 'xnet', 'xns-idp', 'xtp', 'zero']

In [35]:
shuffled_balanced_data["state"].unique()

['FIN', 'CON', 'INT', 'REQ', 'RST', 'ECO', 'PAR', 'URN', 'no']
Categories (9, object): ['CON', 'ECO', 'FIN', 'INT', ..., 'REQ', 'RST', 'URN', 'no']

In [36]:
shuffled_balanced_data["service"].unique()

['-', 'http', 'ftp', 'smtp', 'ftp-data', ..., 'snmp', 'dhcp', 'ssl', 'irc', 'radius']
Length: 13
Categories (13, object): ['-', 'dhcp', 'dns', 'ftp', ..., 'smtp', 'snmp', 'ssh', 'ssl']

# **Scalling Using Log Scale**

In [37]:
X = shuffled_balanced_data.drop("label",axis=1)
y = shuffled_balanced_data["label"]

In [38]:
X.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt',
       'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt',
       'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_src_dport_ltm', 'ct_dst_sport_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'is_sm_ips_ports'],
      dtype='object')

In [39]:
numeric_cols = X.select_dtypes(include=[np.number]).columns
numeric_cols

Index(['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sload', 'dload',
       'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb',
       'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean',
       'trans_depth', 'response_body_len', 'ct_src_dport_ltm',
       'ct_dst_sport_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd',
       'is_sm_ips_ports'],
      dtype='object')

In [40]:
X[numeric_cols] = np.log1p(X[numeric_cols])

In [41]:
X.head(3)

c:\Users\mosta\anaconda3\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,smean,dmean,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports
0,0.039132,tcp,-,FIN,4.510859,4.532599,8.551595,11.336343,8.419896,13.840944,...,4.060443,6.815640,0.000000,0.000000,0.693359,0.693359,0.0,0.0,0.000000,0.0
1,0.554810,tcp,-,FIN,2.397895,2.197225,6.336826,5.872118,3.174845,8.609037,...,4.043051,3.806663,0.000000,0.000000,0.693359,0.693359,0.0,0.0,0.000000,0.0
2,0.872379,tcp,http,FIN,3.295837,4.744932,7.308543,11.873784,4.613272,9.017313,...,4.060443,7.138073,0.693147,11.144684,0.693359,0.693359,0.0,0.0,0.693359,0.0

In [42]:
X["is_sm_ips_ports"].unique()

array([0.    , 0.6934], dtype=float16)

# **Encoding Using get_dummies**

In [43]:
X = pd.get_dummies( X , dtype=int )

In [44]:
X.head()

,dur,spkts,dpkts,sbytes,dbytes,rate,sload,dload,sloss,dloss,...,service_ssl,state_CON,state_ECO,state_FIN,state_INT,state_PAR,state_REQ,state_RST,state_URN,state_no
0,0.039132,4.510859,4.532599,8.551595,11.336343,8.419896,13.840944,16.626022,2.079442,3.688879,...,0,0,0,1,0,0,0,0,0,0
1,0.554810,2.397895,2.197225,6.336826,5.872118,3.174845,8.609037,8.115245,1.098612,0.693147,...,0,0,0,1,0,0,0,0,0,0
2,0.872379,3.295837,4.744932,7.308543,11.873784,4.613272,9.017313,13.613241,1.098612,4.025352,...,0,0,0,1,0,0,0,0,0,0
3,0.013628,2.833213,2.944439,7.340187,7.405496,7.785751,13.643443,13.716214,1.609438,1.609438,...,0,0,0,1,0,0,0,0,0,0
4,1.737207,3.218876,3.135494,7.123673,7.396949,2.362023,7.617193,7.886082,2.079442,2.302585,...,0,0,0,1,0,0,0,0,0,0

# **Splitting Data**

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state = 42 , stratify = y , test_size = .2)

In [47]:
print(X_train.shape)
print(X_test.shape)

(77457, 186)
(19365, 186)

In [48]:
X_train.describe()

c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
c:\Users\mosta\anaconda3\Lib\site-packages\numpy\_core\_methods.py:53: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:731: RuntimeWarning: invalid value encountered in scalar divide
  the_mean = the_sum / count if count > 0 else np.nan
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
c:\Users\mosta\anaconda3\Lib\site-packages\pandas\core\nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)

,dur,spkts,dpkts,sbytes,dbytes,rate,sload,dload,sloss,dloss,...,service_ssl,state_CON,state_ECO,state_FIN,state_INT,state_PAR,state_REQ,state_RST,state_URN,state_no
count,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,...,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.000000,77457.0
mean,0.496857,2.662913,2.400722,7.213092,6.565682,5.489781,11.539782,9.600058,1.325633,1.338397,...,0.000594,0.113728,0.000103,0.768129,0.110771,0.000013,0.006365,0.000878,0.000013,0.0
std,0.636942,1.092075,1.345524,1.545471,3.068602,3.031520,3.438503,4.445621,0.992317,1.218440,...,0.024363,0.317482,0.010162,0.422030,0.313851,0.003593,0.079526,0.029617,0.003593,0.0
min,0.000000,0.693147,0.000000,3.850148,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,0.017625,2.197225,1.945910,6.336826,5.594711,3.240714,9.020040,7.996304,1.098612,0.693147,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
50%,0.368549,2.397895,2.197225,6.953684,6.549651,4.167887,10.485780,9.212375,1.098612,1.098612,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
75%,0.702754,3.218876,3.135494,7.992607,8.221748,7.948452,13.372632,13.330943,2.079442,2.079442,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
max,4.110874,9.158310,9.303375,16.348763,16.500330,13.815512,22.513023,16.922472,8.465057,8.609773,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

# **Model Trainning**

In [49]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC

In [ ]:
DT = DecisionTreeClassifier(random_state=42)
RF = RandomForestClassifier(n_estimators=50, random_state=42)
LR = LogisticRegression(max_iter=1000)

In [51]:
from sklearn.ensemble import VotingClassifier

In [52]:
ensemble_model = VotingClassifier(
    estimators=[
        ('lr', LR),
        ('dt', DT), 
        ('rf', RF), 
    ],
    voting='hard' 
)

# **Evaluation**

In [53]:
from sklearn.metrics import classification_report, accuracy_score , confusion_matrix

In [54]:
ensemble_model.fit(X_train, y_train)
y_pred = ensemble_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

c:\Users\mosta\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 0.9152594887683966

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.88      0.91      9779
           1       0.89      0.95      0.92      9586

    accuracy                           0.92     19365
   macro avg       0.92      0.92      0.92     19365
weighted avg       0.92      0.92      0.92     19365

In [55]:
DT.fit(X_train, y_train)
y_pred = DT.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9052930544797315

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.91      0.91      9779
           1       0.91      0.90      0.90      9586

    accuracy                           0.91     19365
   macro avg       0.91      0.91      0.91     19365
weighted avg       0.91      0.91      0.91     19365

In [56]:
RF.fit(X_train, y_train)
y_pred = RF.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9189258972372838

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.90      0.92      9779
           1       0.90      0.94      0.92      9586

    accuracy                           0.92     19365
   macro avg       0.92      0.92      0.92     19365
weighted avg       0.92      0.92      0.92     19365

In [57]:
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8557707203718048

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.81      0.85      9779
           1       0.82      0.91      0.86      9586

    accuracy                           0.86     19365
   macro avg       0.86      0.86      0.86     19365
weighted avg       0.86      0.86      0.86     19365

c:\Users\mosta\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [58]:
import pickle

In [59]:
with open('model.pkl', 'wb') as file:
    pickle.dump(ensemble_model, file)